"""Create User, Product, Purchase tables

Revision ID: 26ec461a7c10
Revises:
Create Date: 2024-12-15 16:39:11.227943

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ec461a7c10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'products',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    )
    op.create_table(
        'users',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
        sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    )
    op.create_table(
        'purchases',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('purchase_date', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'], name=op.f('fk_purchases_user_id_users'), ondelete='cascade'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_purchases')),
    )
    op.create_table(
        'product_purchase',
        sa.Column('product_id', sa.UUID(), nullable=False),
        sa.Column('purchase_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['product_id'],
            ['products.id'],
            name=op.f('fk_product_purchase_product_id_products'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['purchase_id'],
            ['purchases.id'],
            name=op.f('fk_product_purchase_purchase_id_purchases'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('product_id', 'purchase_id', name=op.f('pk_product_purchase')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_purchase')
    op.drop_table('purchases')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
